name: Test, Build, Push

env:
  APP_NAME: xuexigithubactions
  VERSION: ${{ github.run_number }}

on:
  workflow_dispatch:
    inputs:
      containerEnv:
        description: "Docker Environment"
        required: true
        default: "docker-dev"
        type: choice
        options:
          - docker-dev
          - docker-stage
          - docker-prod
      buildEnv:
        description: "Build Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - stage
          - prod
      deployToK8:
        description: "Deploy to K8"
        required: false
        type: boolean

jobs:
  test_build_push:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: echo "Running tests....."

      - name: Build code
        run: echo "Running build....."

      - name: Build image
        run: echo "Building image....."

      - name: Push image
        run: echo "Pushing to ${{ inputs.containerEnv }} registry"

  deploy_to_iks:
    if: ${{ inputs.deployToK8 == true }}
    needs: test_build_push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Deploy to ${{ inputs.deployToK8 }} k8 with ${{ inputs.buildEnv }} build from ${{ inputs.containerEnv }} in progress....."
